name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.5.0
  - ipython=8.14.0
  - notebook=7.0.1
  - jupyterlab=4.0.3
  - cookiecutter=2.2.3
  - hydra-core=1.3.2
  - matplotlib=3.7.2
  - pandas=1.5.3
  - git=2.30.2
  - pip=23.2.1
  - pip:
      - wandb==0.15.8
