name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.2.1
  - mlflow=2.5.0
  - scikit-learn=1.2.2
  - matplotlib=3.7.2
  - pillow=10.0.0
  - pip:
      - wandb==0.15.8
