name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=23.2.1
  - ydata-profiling=4.3.2
  - pyarrow=12.0.1
  - pip:
      - wandb==0.15.8
